//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WeatherForecastEntities1 : DbContext
    {
        public WeatherForecastEntities1()
            : base("name=WeatherForecastEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblDaily> tblDailies { get; set; }
        public virtual DbSet<tblHourly> tblHourlies { get; set; }
        public virtual DbSet<tblMinutely> tblMinutelies { get; set; }
        public virtual DbSet<tblWeatherDataResponse> tblWeatherDataResponses { get; set; }
    }
}
