//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHourly
    {
        public int Id { get; set; }
        public int weatherDataResponseId { get; set; }
        public string Summary { get; set; }
        public string Icon { get; set; }
        public Nullable<decimal> PrecipIntensity { get; set; }
        public Nullable<decimal> precipProbability { get; set; }
        public string precipType { get; set; }
        public Nullable<decimal> Temperature { get; set; }
        public Nullable<decimal> apparentTemperature { get; set; }
        public Nullable<decimal> DewPoint { get; set; }
        public Nullable<decimal> Humidity { get; set; }
        public Nullable<decimal> Pressure { get; set; }
        public Nullable<decimal> windSpeed { get; set; }
        public Nullable<decimal> windGust { get; set; }
        public Nullable<decimal> windBearing { get; set; }
        public Nullable<decimal> UvIndex { get; set; }
        public Nullable<decimal> CloudCover { get; set; }
        public Nullable<decimal> Visibility { get; set; }
        public Nullable<decimal> Ozone { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual tblWeatherDataResponse tblWeatherDataResponse { get; set; }
    }
}
