//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMinutely
    {
        public int Id { get; set; }
        public int weatherDataResponseId { get; set; }
        public string Summary { get; set; }
        public string Icon { get; set; }
        public Nullable<decimal> PrecipIntensity { get; set; }
        public Nullable<decimal> PrecipIntensityError { get; set; }
        public Nullable<decimal> precipProbability { get; set; }
        public string precipType { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual tblWeatherDataResponse tblWeatherDataResponse { get; set; }
    }
}
