//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelData
{
    using System;
    using System.Collections.Generic;
    using System.Xml.Serialization;

    public partial class tblWeatherDataResponse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblWeatherDataResponse()
        {
            this.tblDailies = new List<tblDaily>();
            this.tblHourlies = new List<tblHourly>();
            this.tblMinutelies = new List<tblMinutely>();
        }
    
        public int weatherDataResponseId { get; set; }
        public Nullable<decimal> Lat { get; set; }
        public Nullable<decimal> Long { get; set; }
        public string TimeZone { get; set; }
        public Nullable<decimal> ApparentTemperature { get; set; }
        public Nullable<decimal> Pressure { get; set; }
        public Nullable<decimal> CloudCover { get; set; }
        public Nullable<decimal> DewPoint { get; set; }
        public Nullable<decimal> Humidity { get; set; }
        public Nullable<decimal> PrecipIntensity { get; set; }
        public Nullable<decimal> MoonPhase { get; set; }
        public Nullable<decimal> Ozone { get; set; }
        public Nullable<decimal> PrecipProbability { get; set; }
        public Nullable<System.DateTime> SunriseTime { get; set; }
        public Nullable<System.DateTime> SunseTime { get; set; }
        public Nullable<System.DateTime> RequestTime { get; set; }
        public Nullable<decimal> Temperature { get; set; }
        public Nullable<int> UvIndex { get; set; }
        public string Summary { get; set; }
        public string Icon { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadWrite")]
        public virtual List<tblDaily> tblDailies { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual List<tblHourly> tblHourlies { get; set; }

       
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual List<tblMinutely> tblMinutelies { get; set; }
    }
}
