//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace MvcWebAPI.DataConversionRef {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DataConversionSoap", Namespace="http://tempuri.org/")]
    public partial class DataConversion : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback farenhiteToCelsiusOperationCompleted;
        
        private System.Threading.SendOrPostCallback celsiusTofarenhiteOperationCompleted;
        
        private System.Threading.SendOrPostCallback saveLiveWeatherDataToDBOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DataConversion() {
            this.Url = global::MvcWebAPI.Properties.Settings.Default.MvcWebAPI_DataConversionRef_DataConversion;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event farenhiteToCelsiusCompletedEventHandler farenhiteToCelsiusCompleted;
        
        /// <remarks/>
        public event celsiusTofarenhiteCompletedEventHandler celsiusTofarenhiteCompleted;
        
        /// <remarks/>
        public event saveLiveWeatherDataToDBCompletedEventHandler saveLiveWeatherDataToDBCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/farenhiteToCelsius", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double farenhiteToCelsius(double fahrenheit) {
            object[] results = this.Invoke("farenhiteToCelsius", new object[] {
                        fahrenheit});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void farenhiteToCelsiusAsync(double fahrenheit) {
            this.farenhiteToCelsiusAsync(fahrenheit, null);
        }
        
        /// <remarks/>
        public void farenhiteToCelsiusAsync(double fahrenheit, object userState) {
            if ((this.farenhiteToCelsiusOperationCompleted == null)) {
                this.farenhiteToCelsiusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfarenhiteToCelsiusOperationCompleted);
            }
            this.InvokeAsync("farenhiteToCelsius", new object[] {
                        fahrenheit}, this.farenhiteToCelsiusOperationCompleted, userState);
        }
        
        private void OnfarenhiteToCelsiusOperationCompleted(object arg) {
            if ((this.farenhiteToCelsiusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.farenhiteToCelsiusCompleted(this, new farenhiteToCelsiusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/celsiusTofarenhite", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double celsiusTofarenhite(double celsius) {
            object[] results = this.Invoke("celsiusTofarenhite", new object[] {
                        celsius});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void celsiusTofarenhiteAsync(double celsius) {
            this.celsiusTofarenhiteAsync(celsius, null);
        }
        
        /// <remarks/>
        public void celsiusTofarenhiteAsync(double celsius, object userState) {
            if ((this.celsiusTofarenhiteOperationCompleted == null)) {
                this.celsiusTofarenhiteOperationCompleted = new System.Threading.SendOrPostCallback(this.OncelsiusTofarenhiteOperationCompleted);
            }
            this.InvokeAsync("celsiusTofarenhite", new object[] {
                        celsius}, this.celsiusTofarenhiteOperationCompleted, userState);
        }
        
        private void OncelsiusTofarenhiteOperationCompleted(object arg) {
            if ((this.celsiusTofarenhiteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.celsiusTofarenhiteCompleted(this, new celsiusTofarenhiteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/saveLiveWeatherDataToDB", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int saveLiveWeatherDataToDB(ModelData.tblWeatherDataResponse _tblWeatherDataResponse) {
            object[] results = this.Invoke("saveLiveWeatherDataToDB", new object[] {
                        _tblWeatherDataResponse});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void saveLiveWeatherDataToDBAsync(tblWeatherDataResponse _tblWeatherDataResponse) {
            this.saveLiveWeatherDataToDBAsync(_tblWeatherDataResponse, null);
        }
        
        /// <remarks/>
        public void saveLiveWeatherDataToDBAsync(tblWeatherDataResponse _tblWeatherDataResponse, object userState) {
            if ((this.saveLiveWeatherDataToDBOperationCompleted == null)) {
                this.saveLiveWeatherDataToDBOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsaveLiveWeatherDataToDBOperationCompleted);
            }
            this.InvokeAsync("saveLiveWeatherDataToDB", new object[] {
                        _tblWeatherDataResponse}, this.saveLiveWeatherDataToDBOperationCompleted, userState);
        }
        
        private void OnsaveLiveWeatherDataToDBOperationCompleted(object arg) {
            if ((this.saveLiveWeatherDataToDBCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.saveLiveWeatherDataToDBCompleted(this, new saveLiveWeatherDataToDBCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class tblWeatherDataResponse {
        
        private int weatherDataResponseIdField;
        
        private System.Nullable<decimal> latField;
        
        private System.Nullable<decimal> longField;
        
        private string timeZoneField;
        
        private System.Nullable<decimal> apparentTemperatureField;
        
        private System.Nullable<decimal> pressureField;
        
        private System.Nullable<decimal> cloudCoverField;
        
        private System.Nullable<decimal> dewPointField;
        
        private System.Nullable<decimal> humidityField;
        
        private System.Nullable<decimal> precipIntensityField;
        
        private System.Nullable<decimal> moonPhaseField;
        
        private System.Nullable<decimal> ozoneField;
        
        private System.Nullable<decimal> precipProbabilityField;
        
        private System.Nullable<System.DateTime> sunriseTimeField;
        
        private System.Nullable<System.DateTime> sunseTimeField;
        
        private System.Nullable<System.DateTime> requestTimeField;
        
        private System.Nullable<decimal> temperatureField;
        
        private System.Nullable<int> uvIndexField;
        
        private string summaryField;
        
        private string iconField;
        
        private System.Nullable<System.DateTime> entryDateField;
        
        private System.Nullable<bool> isActiveField;
        
        /// <remarks/>
        public int weatherDataResponseId {
            get {
                return this.weatherDataResponseIdField;
            }
            set {
                this.weatherDataResponseIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> Lat {
            get {
                return this.latField;
            }
            set {
                this.latField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> Long {
            get {
                return this.longField;
            }
            set {
                this.longField = value;
            }
        }
        
        /// <remarks/>
        public string TimeZone {
            get {
                return this.timeZoneField;
            }
            set {
                this.timeZoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> ApparentTemperature {
            get {
                return this.apparentTemperatureField;
            }
            set {
                this.apparentTemperatureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> Pressure {
            get {
                return this.pressureField;
            }
            set {
                this.pressureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> CloudCover {
            get {
                return this.cloudCoverField;
            }
            set {
                this.cloudCoverField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> DewPoint {
            get {
                return this.dewPointField;
            }
            set {
                this.dewPointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> Humidity {
            get {
                return this.humidityField;
            }
            set {
                this.humidityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> PrecipIntensity {
            get {
                return this.precipIntensityField;
            }
            set {
                this.precipIntensityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> MoonPhase {
            get {
                return this.moonPhaseField;
            }
            set {
                this.moonPhaseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> Ozone {
            get {
                return this.ozoneField;
            }
            set {
                this.ozoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> PrecipProbability {
            get {
                return this.precipProbabilityField;
            }
            set {
                this.precipProbabilityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> SunriseTime {
            get {
                return this.sunriseTimeField;
            }
            set {
                this.sunriseTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> SunseTime {
            get {
                return this.sunseTimeField;
            }
            set {
                this.sunseTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> RequestTime {
            get {
                return this.requestTimeField;
            }
            set {
                this.requestTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> Temperature {
            get {
                return this.temperatureField;
            }
            set {
                this.temperatureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> UvIndex {
            get {
                return this.uvIndexField;
            }
            set {
                this.uvIndexField = value;
            }
        }
        
        /// <remarks/>
        public string Summary {
            get {
                return this.summaryField;
            }
            set {
                this.summaryField = value;
            }
        }
        
        /// <remarks/>
        public string Icon {
            get {
                return this.iconField;
            }
            set {
                this.iconField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> EntryDate {
            get {
                return this.entryDateField;
            }
            set {
                this.entryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void farenhiteToCelsiusCompletedEventHandler(object sender, farenhiteToCelsiusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class farenhiteToCelsiusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal farenhiteToCelsiusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void celsiusTofarenhiteCompletedEventHandler(object sender, celsiusTofarenhiteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class celsiusTofarenhiteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal celsiusTofarenhiteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void saveLiveWeatherDataToDBCompletedEventHandler(object sender, saveLiveWeatherDataToDBCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class saveLiveWeatherDataToDBCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal saveLiveWeatherDataToDBCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591